#pragma once
#include <iostream>
#include <string>
#include "pov_object.h"

namespace POV {
	//class for models generated by poseRay
	class POVModel: POVObject{
		friend class POVParser; 
		Location m_lc;
		std::string m_texture;
	public:
		POVModel(const std::string & object);
		~POVModel();
		bool setLocation(Location _lc);
		bool setLocation(float _x, float _y, float _z);

		//use a .png image as the texture of the generated model
		bool setTexture(const std::string & _png);

	protected:  //users cannot directly parser this object to .pov
		bool parserPOV(std::ofstream & os);
	};
}