#include "pov_object.h"
#include <list>

namespace POV
{
    class POVParser{
        std::list<POVObject *> objs; 
    public:
        //Construction and destruction
        POVParser();
        ~POVParser();

        //import a model generated by poseRay
        //this function will auto include the .inc file of generated model
        //when not finding the suitable file, return false
        bool importObject(const std::string & object_name);

        bool importObject(POVModel * pov_model);

        bool setCamera(POVCamera* camera);

        bool setLightSource(POVLightSource * lightsource);

        bool setbackground(POVBackGround * bg);

        bool addObject(POVObject * obj);
        //parser the scene to a .pov file
        bool parserPOV(const std::string & _file_name);
    };
} // namespace POV